lumino/main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'shared.views.custom_404'
handler403 = 'shared.views.custom_403'

urlpatterns = (
    [
        path('i18n/', include('django.conf.urls.i18n')),
    ]
    + i18n_patterns(
        path('subjects/', include('subjects.urls')),
        path('admin/', admin.site.urls),
        path('django-rq/', include('django_rq.urls')),
        path('', include('users.urls')),
        path('', include('shared.urls')),
        path('', include('accounts.urls')),
        path('', include('django.conf.urls.i18n')),
    )
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

lumino/users/urls.py
from django.urls import path, register_converter

from . import converters, views

app_name = 'users'

register_converter(converters.ProfileConverter, 'profile')

urlpatterns = [
    path('user/edit/', views.user_edit, name='edit-profile'),
    path('user/leave/', views.user_leave, name='delete-profile'),
    path('users/<profile:profile>/', views.user_detail, name='profile-detail'),
]

lumino/users/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Profile(models.Model):
    class Role(models.TextChoices):
        STUDENT = 'S', 'Student'
        TEACHER = 'T', 'Teacher'

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE
    )
    avatar = models.ImageField(upload_to='avatars', default='avatars/noavatar.png', blank=True)
    bio = models.TextField(max_length=265, blank=True)
    role = models.CharField(max_length=1, choices=Role, default=Role.STUDENT)

    def __str__(self):
        return f'Profile of {self.user.username}'

    def is_student(self):
        return self.role == self.Role.STUDENT

    def is_teacher(self):
        return self.role == self.Role.TEACHER

    def get_absolute_url(self):
        return reverse('users:profile-detail', args=[self.user.username])

    def get_full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'

lumino/users/forms.py
from django import forms

from .models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'avatar']

lumino/users/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils.translation import gettext as _

from shared.decorators import student_required

from .forms import EditProfileForm
from .models import Profile


@login_required
def user_detail(request, profile: Profile):
    return render(request, 'users/profile/detail.html', {'profile': profile})


@login_required
def user_edit(request):
    profile = request.user.profile
    if request.method == 'POST':
        if (form := EditProfileForm(request.POST, request.FILES, instance=profile)).is_valid():
            profile = form.save()
            messages.success(request, _('User profile has been successfully saved.'))
            return redirect('users:profile-detail', profile.user.username)
    form = EditProfileForm(instance=profile)
    return render(request, 'users/profile/edit.html', {'form': form})


@login_required
@student_required
def user_leave(request):
    request.user.delete()
    logout(request)
    messages.success(request, _('Good bye! Hope to see you soon.'))
    return redirect('index')

lumino/users/templates/users/profile/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}

{% block content %}
<div class="container-fluid mt-5 pt-5 d-flex justify-content-center">
  <div class="bg-secondary-subtle rounded d-flex flex-column align-items-center p-5 g-3">
    {% thumbnail profile.avatar "200x200" crop="center" format="PNG" as thumb %}
        <img class="rounded" src="{{ thumb.url }}" alt="{{profile.get_full_name}} avatar">
    {% endthumbnail %}
    <h1>{{profile.get_full_name}}</h1>
    <h2>{{profile.get_role_display}}</h2>
    <h2>{{profile.user.email}}</h2>
    <textarea name="bio" id="bio" class="w-100" rows="5" readonly>{{profile.bio}}</textarea>
    {% if profile.user == user %}
      <div class="btn-group mt-3" role="group" aria-label="Account actions">
        <a href="{% url "users:edit-profile" %}" class="btn btn-outline-warning">{% translate "Edit" %}</a>
        {% if profile.is_student %}
          <a href="{% url "users:delete-profile" %}" class="btn btn-danger">Delete account</a>
        {% endif %}
      </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

lumino/users/templates/users/profile/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="d-flex w-100 h-100 justify-content-center align-items-center">
    <form id="edit-profile" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary w-100 mt-3 mb-2">{% translate 'Edit Profile' %}</button>
    </form>
</div>
{% endblock content %}